### ISSUE TITLE
New messages appear stacked over each other

### ISSUE THREAD

**Issue by ElektroKill** [DiscordStyles/MinimalCord#20]
![image](https://user-images.githubusercontent.com/37494960/134564177-486293f1-d8cc-406f-a9a3-fde3a2473938.png)

**Comment by Gibbu** [comment]
If you just used the issue template that is provided, you could've seen what I require to actually fix stuff.

**Comment by ElektroKill** [comment]
I’m sorry but there is no issue template defined in this repository. There is one in the Slate them repository but not here :/

**Comment by DS-GitHub** [comment]
@Gibbu 
**Describe the bug**  
*((A clear and concise description of what the bug is))*  
Messages with unread line appear stacked over each other.

**To Reproduce**  
*((Steps to reproduce the behavior))*  
1. Receive new message and see the channel or Select display unread at any message.

**Screenshots**  
*((If applicable, add screenshots to help explain your problem))*  
bug:
![image](https://user-images.githubusercontent.com/37930090/135410271-d3a3ff19-ac91-43bf-b3d8-ab586e689507.png)
normal:
![image](https://user-images.githubusercontent.com/37930090/135410403-6b4e5af2-6231-49d6-823b-fb34e01b2cff.png)

**Infomation (please complete the following information):**  
Discord channel: *((Stable/PTB/Canary))*  Canary
OS: *((Windows/Linux/OSX))*  Windows 10
Mod: *((BetterDiscord/Powercord/Vizality))* BetterDiscord 
Discord language: *((Your language))*  Korean

**Additional context**  
*((Add any other context about the problem here.))*

**Comment by Gibbu** [comment]
@ElektroKill Ahh that's my bad. I thought I had a bug report on here as well. Must've missed it.

And this *seems* to be a pretty easy fix.

**Comment by Gibbu** [comment]
Fixed.
