### ISSUE TITLE
MinimalCord for Powercord appears to be broken following a Discord update

### ISSUE THREAD

**Issue by piqey** [DiscordStyles/MinimalCord#22]
**Describe the bug**  
Recent Discord update bricked a lot of themes, guess all the classes were reassigned. Not sure if the theme is even loading, hard to tell.

**To Reproduce**  
Install theme, reload Discord

**Screenshots**  
Discord is just the ugly vanilla theme  

**Information (please complete the following information):**  
Discord channel: Canary
OS: Windows
Mod: Powercord
Discord language: English

**Additional context**  
I understand if the focus of DiscordStyles is no longer on MinimalCord; I would be using [Fluent](https://github.com/DiscordStyles/Fluent) but it appears to have the same issue. MinimalCord is my theme of choice.

**Comment by Gibbu** [comment]
The newest Canary update did change most if not all classes so the theme *is* working, just selecting classes that don't exist.
Once the update comes to Stable it will be fixed.

The only themes that I don't really have focus on is iPadOS and SimplyDark as I find those boring to work on.

**Comment by toydotgame** [comment]
> Not sure if the theme is even loading, hard to tell.

The theme is loading fine. I use my own CSS and then paste [MinimalCord's full CSS](https://discordstyles.github.io/MinimalCord/dist/MinimalCord.css) under it, so that [most of] it all loads locally (a bit faster, given my awful internet sometimes); I updated my part of the CSS this morning to the new classes and the file seems to be perfectly operational.

Might also add that I'm on BetterDiscord:
![image](https://user-images.githubusercontent.com/64190512/148867591-21be160f-4819-46bf-a6be-f830ff1f9243.png)

**Comment by piqey** [comment]
> > Not sure if the theme is even loading, hard to tell.
> 
> The theme is loading fine. I use my own CSS and then paste [MinimalCord's full CSS](https://discordstyles.github.io/MinimalCord/dist/MinimalCord.css) under it, so that [most of] it all loads locally (a bit faster, given my awful internet sometimes); I updated my part of the CSS this morning to the new classes and the file seems to be perfectly operational.
> 
> Might also add that I'm on BetterDiscord: ![image](https://user-images.githubusercontent.com/64190512/148867591-21be160f-4819-46bf-a6be-f830ff1f9243.png)

That trick does indeed work. Thanks for the help!

**Comment by toydotgame** [comment]
That…wasn't meant to be a trick that was meant to work; it was just meant to save me loading time when I opened Discord because it didn't have to download the CSS from the internet.

Turns out that there were a few updates to MinimalCord since I made that reply.
![image](https://user-images.githubusercontent.com/64190512/149050190-9673606b-05e0-416d-b9a4-9a73b4bc1050.png)
That seems to be what fixed it. I copied in the CSS again and the line count has definitely changed, and everything works now too.
![image](https://user-images.githubusercontent.com/64190512/149050336-dd41a2a8-2810-4592-81ce-6cb690d951ee.png)

***

###### A note for BetterDiscord users, too: there are still some graphical issues regardless of custom CSS that are being worked on. An example is things like the header and check box on this page in settings: (Note the black text and awful spacing. This is not MinimalCord's fault)
![image](https://user-images.githubusercontent.com/64190512/149050484-cbdec6ee-ce17-4099-8ab9-7f2e110014b9.png)
